---
- hosts: all
  remote_user:  ubuntu
  become:       true
  become_user:  root
  become_method: sudo
    
  tasks:
  # Set our hostname
  - name:  Set our hostname
    hostname:
      name:  "{{ HOSTNAME }}"

  # Install base packages
  - name:  Install base packages
    apt:
      name:  "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - htop
      - zsh
      - s3cmd

  # Create .s3cfg
  - name:  Create .s3cfg
    template:
      src:  s3cfg.j2
      dest: /home/ubuntu/.s3cfg
      owner: ubuntu
      group: ubuntu

  # Copy key.pem
  - name:  Copy key.pem
    copy:
      src:  key.pem
      dest: /etc/ssl/private
      mode: 0400

  # Install Python modules for AWS tasks
  - name:  Install pip
    apt:
      name: python-pip
      state: present
  - name:  Install Python modules for AWS tasks
    pip:
      name:  boto
      state: present

  # Create Amazon RDS database
  - name:  Create AWS RDS database
    rds:
      aws_access_key:      "{{ AWS_RDS_ACCESS_KEY }}"
      aws_secret_key:      "{{ AWS_RDS_SECRET_KEY }}"
      command:             create
      db_engine:           MySQL
      region:              us-east-2
      vpc_security_groups: "{{ AWS_RDS_SECURITY_GROUP }}"
      instance_name:       "{{ OPERATING_ENVIRONMENT }}-mysql"
      instance_type:       db.t2.micro
      username:            "{{ MYSQL_ADMIN_USERNAME }}"
      password:            "{{ MYSQL_ADMIN_PASSWORD }}"
      publicly_accessible: no
      size:                10
      wait:                yes
      wait_timeout:        900
    register:  rds

  - name:  Install MySQL dependencies
    apt:
      name:  "{{ item }}"
      state: present
    with_items:
      - mysql-client
      - libmysqlclient-dev

  - name:  Install Python modules for MySQL tasks
    pip:
      name:  mysql-python
      state: present

  - name:  Create MySQL database
    mysql_db:
      login_host:      "{{ rds.instance.endpoint }}"
      login_user:      "{{ MYSQL_ADMIN_USERNAME }}"
      login_password:  "{{ MYSQL_ADMIN_PASSWORD }}"
      name:            helloworld
      state:           present

  # Create /etc/environment
  # /etc/environment references our RDS output
  - name:  Create /etc/environment
    template:
      src:  environment.j2
      dest: /etc/environment

  # Create .my.cnf
  - name:  Create .my.cnf
    blockinfile:
      create:  yes
      path:    /home/ubuntu/.my.cnf
      owner:   ubuntu
      group:   ubuntu
      block: |
        [client]
        host="{{ rds.instance.endpoint }}"
        user="{{ MYSQL_ADMIN_USERNAME }}"
        password="{{ MYSQL_ADMIN_PASSWORD }}"
    tags: mycnf



  # Display all variables
  - name:  Display variables
    debug:  var=hostvars[inventory_hostname]
    tags:  ['never', 'debug']
