---
- hosts: all
  remote_user:  ubuntu
  become:       true
  become_user:  root
  become_method: sudo
  tasks:
  # Set our hostname
  - name:  Set our hostname
    hostname:
      name:  ansible-helloworld

  # Install base packages
  - name:  Install base packages
    apt:
      name:  "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - htop
      - zsh
