---
# Create users for production servers
- block:
  - name:  Create users for production servers
    user:
      name:  "{{ item.name }}"
      state: present
      groups: "{{ item.groups }}"
      shell:  "{{ item.shell }}"
    loop:  "{{ users }}"
  - name:  Create authorized_keys for production server users
    authorized_key:
      user:  "{{ item.name }}"
      state: present
      key: "{{ lookup('file', '{{ ssh_keys/item.name }}') }}"
    loop:  "{{ users }}"
  - name: Allow 'operations' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%operations'
      line: '%operations ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
  - name: Allow 'architects' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%architects'
      line: '%architects ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
  when:
    - "'production' in group_names"
    - "('architects' in item.groups) or
       ('operations' in item.groups)"
