---
# Create users for staging servers
- block:
  - name:  Create users for staging servers
    user:
      name:  "{{ item.name }}"
      state: present
      groups: "{{ item.groups }}"
      shell:  "{{ item.shell }}"
    loop:  "{{ users }}"
  - name:  Create authorized_keys for staging server users
    authorized_key:
      user:  "{{ item.name }}"
      state: present
      key: "{{ lookup('file', 'ssh_keys/{{ item.name }}') }}"
    loop:  "{{ users }}"
  when:
    - "'staging' in group_names"
    - "('architects' in item.groups) or
       ('operations' in item.groups) or
       ('developers' in item.groups) or
       ('testers'    in item.groups)"

# Add sudo for appropriate staging users
- name: Allow groups to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    validate: 'visudo -cf %s'
  with_items:
    - {regexp: "^%architects", line:  "%architects ALL=(ALL) NOPASSWD: ALL"}
    - {regexp: "^%operations", line:  "%operations ALL=(ALL) NOPASSWD: ALL"}
    - {regexp: "^%developers", line:  "%developers ALL=(ALL) NOPASSWD: ALL"}
  when: "'staging' in group_names"

